repos:
  - repo: local
    hooks:
      - id: format
        name: format
        language: system
        entry: make
        args: [format]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/crate-ci/typos
    rev: v1.39.0
    hooks:
      - id: typos
