repos:
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
     - id: doctoc
       args: [--update-only]
  - repo: local
    hooks:
      - id: format
        name: format
        language: system
        entry: make
        args: [format]
