# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
right_format = """
${custom.git_master_status}\
${custom.v2raya}\
${custom.ranger}\
${time}
"""

[character]
success_symbol = '\$'
error_symbol = '✗'
vicmd_symbol = 'V'

[[battery.display]]
threshold = 20

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_branch]
symbol = ''
truncation_symbol = ''

[time]
format = '[$time]($style) '
disabled = false

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = "~${count} "
ahead = "⇡${count} "
behind = '⇣${count} '
diverged = '⇡${ahead_count}⇣${behind_count} '
untracked = '[?${count}](white) '
stashed = "[*${count}](black) "
modified = "!${count} "
staged = "[+${count}](green) "
renamed = '»${count} '
deleted = '[-${count}](red) '
style = 'yellow'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[custom.ranger]
command = 'echo $RANGER_LEVEL' # shows output of command
when = ''' [[ -n $RANGER_LEVEL ]] '''
format = '[ $output]($style) '
style = 'yellow'

[custom.v2raya]
when = ''' lsof -nP -iTCP:$V2RAYA_ADDRESS | grep LISTEN '''
format = '[󰰫$output]($style) '

[custom.git_master_status]
command = '''
current_branch=$(git symbolic-ref --short HEAD 2>/dev/null)
if [[ -n $current_branch && $current_branch != "master" ]]; then
  is_merged=$(git branch --merged origin/master | grep -w "$current_branch" || echo "")
  if [[ -n $is_merged ]]; then
    echo "merged"
    exit 0
  fi
fi

ahead=$(git rev-list --count origin/master..HEAD 2>/dev/null || echo "0")
behind=$(git rev-list --count HEAD..origin/master 2>/dev/null || echo "0")

if [[ $ahead -gt 0 && $behind -gt 0 ]]; then
  echo "⇡$ahead⇣$behind"
elif [[ $ahead -gt 0 ]]; then
  echo "⇡$ahead"
elif [[ $behind -gt 0 ]]; then
  echo "⇣$behind"
else
  echo ""
fi
'''
when = 'git rev-parse --is-inside-work-tree &>/dev/null'
format = '[$output]($style) '
style = 'red'

############
# Disabled #
############
[container]
disabled = true

[helm]
disabled = true

[lua]
disabled = true

[docker_context]
disabled = true

[package]
disabled = true
