# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
right_format = """
${custom.v2raya}\
${custom.ranger}\
${time}
"""

[character]
success_symbol = '\$'
error_symbol = '✗'
vicmd_symbol = 'V'

[[battery.display]]
threshold = 20

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_branch]
symbol = ''
truncation_symbol = ''

[time]
format = '[$time]($style) '
disabled = false

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = "~${count} "
ahead = "⇡${count} "
behind = '⇣${count} '
diverged = '⇡${ahead_count}⇣${behind_count} '
untracked = '?${count} '
stashed = "*${count} "
modified = "!${count} "
staged = "+${count} "
renamed = '»${count} '
deleted = '-${count} '
style = 'yellow'

[custom.ranger]
command = 'echo $RANGER_LEVEL' # shows output of command
when = ''' [[ -n $RANGER_LEVEL ]] '''
format = '[ $output]($style) '
style = 'yellow'

[custom.v2raya]
when = ''' lsof -nP -iTCP:$V2RAYA_ADDRESS | grep LISTEN '''
format = '[󰰫$output]($style) '

############
# Disabled #
############
[container]
disabled = true

[helm]
disabled = true

[lua]
disabled = true
