gui:
  windowSize: 'normal' # one of 'normal' | 'half' | 'full' default is 'normal'
  scrollHeight: 10 # how many lines you scroll by
  sidePanelWidth: 0.2 # number from 0 to 1
  mainPanelSplitMode: 'vertical' # one of 'horizontal' | 'flexible' | 'vertical'
  theme:
    selectedLineBgColor:
      - reverse
  showFileTree: false # for rendering changes files in a tree format
  authorColors:
    'kang': 'yellow'
    'Kang Yi': 'yellow'
    '*': 'default'
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showRandomTip: true
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: false
  nerdFontsVersion: '3'
  splitDiff: 'auto' # one of 'auto' | 'always'
  skipRewordInEditorWarning: false # for skipping the confirmation before launching the reword editor
git:
  branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty="%C(yellow)%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" {{branchName}} --'
  overrideGpg: true
  paging:
    colorArg: always
    pager: sed 's/\t/├──┤/g' | delta --paging=never
os:
  edit: 'git diff --name-only --diff-filter=U --relative | grep --quiet --line-regexp {{filename}} && nvim -c "DiffviewOpen -- {{filename}}" || nvim {{filename}}'
  editAtLine: 'git diff --name-only --diff-filter=U --relative | grep --quiet --line-regexp {{filename}} && nvim +{{line}} -c "DiffviewOpen -- {{filename}}" || nvim +{{line}} {{filename}}'
notARepository: 'quit' # one of: 'prompt' | 'create' | 'skip' | 'quit'
promptToReturnFromSubprocess: false # display confirmation when subprocess terminates
keybinding:
  universal:
    quit: 'Q' # <Shift-q>
    return: 'q' # return to previous menu, will quit if there's nowhere to return
    quitWithoutChangingDirectory: 'Q'
customCommands:
  - key: 'c'
    command: 'git diff {{.SelectedFile.Name}} | delta --paging always'
    context: 'files'
    description: 'Show change(diff) in local'
    subprocess: true
  - key: 'C'
    command: 'git diff --cached {{.SelectedFile.Name}} | delta --paging always'
    context: 'files'
    description: 'Show change(diff) in work tree'
    subprocess: true
