#!/bin/sh

if [[ `uname` == 'Darwin' ]]; then
    open raycast://extensions/raycast/raycast/confetti

    # Don't open the main kitty app if we're already in kitty-quick-access
    if [[ "$KITTY_INSTALLATION_DIR" != "/Applications/kitty.app/Contents/kitty-quick-access.app/Contents/Resources/kitty" ]]; then
        open /Applications/kitty.app
    fi
fi


if [ -x ./.git/hooks/post-commit ]; then
    ./.git/hooks/post-commit "$@"
fi
