#!/bin/sh

if [[ `uname` == 'Darwin' ]]; then
    open raycast://extensions/raycast/raycast/confetti

    # If we're in kitty-quick-access, open quick-access terminal
    if [[ "$KITTY_INSTALLATION_DIR" == "/Applications/kitty.app/Contents/kitty-quick-access.app/Contents/Resources/kitty" ]]; then
        kitten quick-access-terminal
    # If we're in the main kitty installation, open the main Kitty app
    elif [[ "$KITTY_INSTALLATION_DIR" == "/Applications/kitty.app/Contents/Resources/kitty" ]]; then
        open /Applications/kitty.app
    fi
fi


if [ -x ./.git/hooks/post-commit ]; then
    ./.git/hooks/post-commit "$@"
fi
