#!/bin/sh

if [ "$(uname)" = "Darwin" ]; then
    open raycast://extensions/raycast/raycast/confetti

    # If we're in the main kitty installation, open the main Kitty app
    if [ "$KITTY_INSTALLATION_DIR" = "/Applications/kitty.app/Contents/Resources/kitty" ]; then
        open /Applications/kitty.app
    fi
fi
