name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Spell Check Repo
        uses: crate-ci/typos@v1.46.0
      - uses: denoland/setup-deno@v2.0.4
        with:
          deno-version: 2.7.14 # Run with latest stable Deno.
      - run: deno fmt --check
