name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - name: Spell Check Repo
        uses: crate-ci/typos@v1.47.2
      - uses: denoland/setup-deno@v2.0.4
        with:
          deno-version: 2.9.0 # Run with latest stable Deno.
      - run: deno fmt --check
