name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Spell Check Repo
        uses: crate-ci/typos@v1.48.0
      - uses: denoland/setup-deno@v2.0.5
        with:
          deno-version: 2.9.3 # Run with latest stable Deno.
      - run: deno fmt --check
